// renderers/angular/a2ui_explorer/src/app/custom-slider.component.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, ChangeDetectionStrategy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {CatalogComponent, createComponentImplementation} from '@a2ui/angular/v0_9';
import z from 'zod';
import {ComponentApi, DynamicStringSchema, DynamicNumberSchema} from '@a2ui/web_core/v0_9';

const customSliderApi = {
  name: 'CustomSlider',
  schema: z.object({
    label: DynamicStringSchema.optional(),
    value: DynamicNumberSchema.optional(),
    min: DynamicNumberSchema.optional(),
    max: DynamicNumberSchema.optional(),
  }),
} satisfies ComponentApi;

/**
 * A custom component not part of any catalog, used to verify the renderer's
 * ability to handle external component types.
 */
@Component({
  selector: 'a2ui-custom-slider',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="custom-slider-container">
      <label>{{ props()['label']?.value() || 'Value' }}: {{ props()['value']?.value() }}</label>
      <input
        type="range"
        [min]="props()['min']?.value() || 0"
        [max]="props()['max']?.value() || 100"
        [value]="props()['value']?.value() || 0"
        (input)="handleInput($event)"
      />
    </div>
  `,
  styles: [
    `
      .custom-slider-container {
        padding: 10px;
        border: 1px dashed blue;
        border-radius: 4px;
      }
      input {
        width: 100%;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomSliderComponent extends CatalogComponent<typeof customSliderApi> {
  handleInput(event: Event) {
    const val = Number((event.target as HTMLInputElement).value);
    this.props()['value']?.onUpdate(val);
  }
}

export const customSliderComponentDeclaration = createComponentImplementation(
  customSliderApi,
  CustomSliderComponent,
);

// renderers/react/a2ui_explorer/src/custom-slider.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {ChangeEvent} from 'react';
import {createComponentImplementation} from '@a2ui/react/v0_9';
import z from 'zod';
import {type ComponentApi, DynamicStringSchema, DynamicNumberSchema} from '@a2ui/web_core/v0_9';

export const customSliderApi = {
  name: 'CustomSlider',
  schema: z.object({
    label: DynamicStringSchema.optional(),
    value: DynamicNumberSchema.optional(),
    min: DynamicNumberSchema.optional(),
    max: DynamicNumberSchema.optional(),
  }),
} satisfies ComponentApi;

/**
 * A custom component not part of any catalog, used to verify the renderer's
 * ability to handle external component types.
 */
export const customSliderComponent = createComponentImplementation(customSliderApi, ({props}) => {
  const label = props.label ?? 'Value';
  const val = typeof props.value === 'number' ? props.value : 0;
  const min = typeof props.min === 'number' ? props.min : 0;
  const max = typeof props.max === 'number' ? props.max : 100;

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const newVal = Number(event.target.value);
    props.setValue?.(newVal);
  };

  return (
    <div
      className="custom-slider-container"
      style={{
        padding: '10px',
        border: '1px dashed blue',
        borderRadius: '4px',
      }}
    >
      <label>
        {label}: {val}
      </label>
      <input
        type="range"
        min={min}
        max={max}
        value={val}
        onChange={handleInput}
        style={{width: '100%'}}
      />
    </div>
  );
});
